/**
 * songs.js
 *
 * The app's songs
 */

window.songs = [
  {
    songId: "SID-1",
    artistId: "AID-231",
    title: "Without Me",
    year: "2018",
    duration: 201,
    url: "https://www.youtube.com/watch?v=YVkUvmDQ3HY",
    explicit: false,
    imgURL: "./images/1.jpg",
  },
  {
    songId: "SID-2",
    artistId: "AID-231",
    title: "Lose Yourself",
    year: "2002",
    duration: 326,
    url: "https://www.youtube.com/watch?v=xFYQQPAOz7Y",
    explicit: false,
    imgURL: "./images/2.jpg",
  },
  {
    songId: "SID-3",
    artistId: "AID-231",
    title: "Stan",
    year: "2000",
    duration: 442,
    url: "https://www.youtube.com/watch?v=gOMhN-hfMtY",
    explicit: false,
    imgURL: "./images/3.jpg",
  },
  {
    songId: "SID-4",
    artistId: "AID-231",
    title: "The Real Slim Shady",
    year: "2000",
    duration: 284,
    url: "https://www.youtube.com/watch?v=eJO5HU_7_1w",
    explicit: false,
    imgURL: "./images/4.jpg",
  },
  {
    songId: "SID-5",
    artistId: "AID-231",
    title: "Mockingbird",
    year: "2023",
    duration: 271,
    url: "https://www.youtube.com/watch?v=S9bCLPwzSC0",
    explicit: false,
    imgURL: "./images/5.jpg",
  },
  {
    songId: "SID-6",
    artistId: "AID-231",
    title: "Not Afraid",
    year: "2010",
    duration: 289,
    url: "https://www.youtube.com/watch?v=j5-yKhDd64s",
    explicit: false,
    imgURL: "./images/6.jpg",
  },
  {
    songId: "SID-7",
    artistId: "AID-231",
    title: "Love The Way You Lie",
    year: "2010",
    duration: 263,
    url: "https://www.youtube.com/watch?v=uelHwf8o7_U",
    explicit: false,
    imgURL: "./images/7.jpg",
  },
  {
    songId: "SID-9",
    artistId: "AID-232",
    title: "Blinding Lights",
    year: "2020",
    duration: 210,
    url: "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    explicit: false,
    imgURL: "./images/2.jpg",
  },
  {
    songId: "SID-10",
    artistId: "AID-232",
    title: "Save Your Tears",
    year: "2021",
    duration: 215,
    url: "https://www.youtube.com/watch?v=XXYlFuWEuKI",
    explicit: true,
    imgURL: "./images/4.jpg",
  },
  {
    songId: "SID-11",
    artistId: "AID-232",
    title: "Can't Feel My Face",
    year: "2015",
    duration: 213,
    url: "https://www.youtube.com/watch?v=KEI4qSrkPAs",
    explicit: false,
    imgURL: "./images/5.jpg",
  },
  {
    songId: "SID-12",
    artistId: "AID-232",
    title: "Starboy",
    year: "2016",
    duration: 230,
    url: "https://www.youtube.com/watch?v=34Na4j8AVgA",
    explicit: false,
    imgURL: "./images/1.jpg",
  },
  {
    songId: "SID-13",
    artistId: "AID-232",
    title: "The Hills",
    year: "2015",
    duration: 242,
    url: "https://www.youtube.com/watch?v=yzTuBuRdAyA",
    explicit: false,
    imgURL: "./images/3.jpg",
  },
  {
    songId: "SID-14",
    artistId: "AID-232",
    title: "In the Night",
    year: "2015",
    duration: 232,
    url: "https://www.youtube.com/watch?v=8gUeyU5Bh_0",
    explicit: false,
    imgURL: "./images/7.jpg",
  },
  {
    songId: "SID-15",
    artistId: "AID-232",
    title: "Earned It",
    year: "2014",
    duration: 257,
    url: "https://www.youtube.com/watch?v=waU75jdUnYw",
    explicit: false,
    imgURL: "./images/6.jpg",
  },
  {
    songId: "SID-16",
    artistId: "AID-233",
    title: "Hotline Bling",
    year: "2015",
    duration: 267,
    url: "https://www.youtube.com/watch?v=uxpDa-c-4Mc",
    explicit: false,
    imgURL: "./images/4.jpg",
  },
  {
    songId: "SID-17",
    artistId: "AID-233",
    title: "In My Feelings",
    year: "2018",
    duration: 217,
    url: "https://www.youtube.com/watch?v=DRS_PpOrUZ4",
    explicit: false,
    imgURL: "./images/7.jpg",
  },
  {
    songId: "SID-18",
    artistId: "AID-233",
    title: "God's Plan",
    year: "2018",
    duration: 215,
    url: "https://www.youtube.com/watch?v=xpVfcZ0ZcFM",
    explicit: false,
    imgURL: "./images/5.jpg",
  },
  {
    songId: "SID-19",
    artistId: "AID-233",
    title: "Started From the Bottom",
    year: "2013",
    duration: 229,
    url: "https://www.youtube.com/watch?v=RubBzkZzpUA",
    explicit: false,
    imgURL: "./images/3.jpg",
  },
  {
    songId: "SID-20",
    artistId: "AID-233",
    title: "One Dance",
    year: "2016",
    duration: 174,
    url: "https://www.youtube.com/watch?v=iIY4B5j2m-E",
    explicit: false,
    imgURL: "./images/1.jpg",
  },
  {
    songId: "SID-21",
    artistId: "AID-233",
    title: "Hold On, We're Going Home",
    year: "2013",
    duration: 230,
    url: "https://www.youtube.com/watch?v=GxgqpCdOKak",
    explicit: false,
    imgURL: "./images/2.jpg",
  },
  {
    songId: "SID-22",
    artistId: "AID-233",
    title: "Nonstop",
    year: "2018",
    duration: 238,
    url: "https://www.youtube.com/watch?v=K4tcOnOuXos",
    explicit: false,
    imgURL: "./images/6.jpg",
  },
];
